// Generated by Parséman 0.18.0 (compiled) — do not edit by hand.
// Source: examples/json/chevrotain-bench.ts
// Rebuild: pnpm build:chevrotain-bench

const _re0 = /"(?:[^\\"]|\\(?:[bfnrtv"\\/]|u[0-9a-fA-F]{4}))*"/y
const _fx0 = ["/\"(?:[^\\\\\"]|\\\\(?:[bfnrtv\"\\\\/]|u[0-9a-fA-F]{4}))*\"/"]
const _fx1 = ["/-?(?:0|[1-9]\\d*)(?:\\.\\d+)?(?:[eE][+-]?\\d+)?/"]
const _fx2 = ["\"{\""]
const _fx3 = ["\":\""]
const _fx4 = ["\"}\""]
const _fx5 = ["\"[\""]
const _fx6 = ["\"]\""]
const _fx7 = ["\"true\""]
const _fx8 = ["\"false\""]
const _fx9 = ["\"null\""]
const _fx10 = ["/\"(?:[^\\\\\"]|\\\\(?:[bfnrtv\"\\\\/]|u[0-9a-fA-F]{4}))*\"/","/-?(?:0|[1-9]\\d*)(?:\\.\\d+)?(?:[eE][+-]?\\d+)?/","\"{\"","\"[\"","\"true\"","\"false\"","\"null\""]

const _pfFail = {}
let _pfEnd

function _tf0(input, _pos, _ctx, _cap) {
  let _e = _pos
  while (_e < input.length) {
    const c = input.charCodeAt(_e)
    let _e0 = _e
    while (_e0 < input.length && (input.charCodeAt(_e0) === 32 || input.charCodeAt(_e0) === 9 || input.charCodeAt(_e0) === 10 || input.charCodeAt(_e0) === 13)) _e0++
    if (_e0 > _e) { _e = _e0; continue }
    break
  }
  if (_cap && _e > _pos) {
    if (_ctx._triviaLog !== undefined) _ctx._triviaLog.push(_pos, _e)
    if (_ctx._cstTriviaLog !== undefined) _ctx._cstTriviaLog.push(_pos, _e, _ctx._cstRawChildren ? _ctx._cstRawChildren.length : 0)
  }
  return _e
}

function _pf1(input, _pos, _ctx) {
  _pfail: {
    const _start31 = _pos
    let _cur32 = _pos
    _re0.lastIndex = _cur32
    const _m33 = _re0.exec(input)
    if (_m33 === null) {
      { _ctx._fe = _cur32; _ctx._fx = _fx0; break _pfail }
    }
    const _v34 = _m33[0]
    _cur32 = _cur32 + _v34.length
    _cur32 = _tf0(input, _cur32, _ctx)
    if (_cur32 >= input.length || input.charCodeAt(_cur32) !== 58) {
      { _ctx._fe = _cur32; _ctx._fx = _fx3; break _pfail }
    }
    const _v35 = ":"
    _cur32 = _cur32 + 1
    _cur32 = _tf0(input, _cur32, _ctx)
    const _pfv36 = _pf0(input, _cur32, _ctx)
    if (_pfv36 === _pfFail) {
      break _pfail
    }
    const _pfe37 = _pfEnd
    _cur32 = _pfe37
    const _arr38 = [_v34, _v35, _pfv36]
    _pfEnd = _cur32
    return _arr38
  }
  return _pfFail
}

function _pf0(input, _pos, _ctx) {
  _pfail: {
    const _code0 = _pos < input.length ? (input.codePointAt(_pos) ?? -1) : -1
    let _chv1, _che2 = _pos
    if (_code0 === 34) {
      _re0.lastIndex = _pos
      const _m3 = _re0.exec(input)
      if (_m3 === null) {
        { _ctx._fe = _pos; _ctx._fx = _fx0; break _pfail }
      }
      const _v4 = _m3[0]
      const _mapped5 = _mf[0](_v4, { start: _pos, end: _pos + _v4.length })
      _chv1 = _mapped5
      _che2 = _pos + _v4.length
    }
    else if (_code0 === 45 || (_code0 >= 48 && _code0 <= 57)) {
      let _e7 = _pos
      let _ok8 = false
      do {
        if (_e7 + 1 <= input.length && (input.charCodeAt(_e7) === 45)) _e7 += 1
        let _ok9 = false
        let _end10 = _e7
        if (_e7 < input.length && (input.charCodeAt(_e7) === 48)) {
          let _e11 = _e7
          let _ok12 = false
          do {
            if (!(_e11 + 1 <= input.length && (input.charCodeAt(_e11) === 48))) break
            _e11 += 1
            _ok12 = true
          } while (false)
          if (!_ok12) _e11 = _e7
          _ok9 = _ok12
          _end10 = _ok12 ? _e11 : _e7
        }
        else if (_e7 < input.length && ((input.charCodeAt(_e7) >= 49 && input.charCodeAt(_e7) <= 57))) {
          let _e13 = _e7
          if (_e7 < input.length && ((input.charCodeAt(_e7) >= 49 && input.charCodeAt(_e7) <= 57))) {
            _e13 = _e7 + 1
            while (_e13 < input.length && ((input.charCodeAt(_e13) >= 48 && input.charCodeAt(_e13) <= 57))) _e13++
          }
          _ok9 = _e13 > _e7
          _end10 = _e13 > _e7 ? _e13 : _e7
        }
        if (!(_ok9)) break
        _e7 = _end10
        let _e14 = _e7
        let _ok15 = false
        do {
          if (!(_e14 + 1 <= input.length && (input.charCodeAt(_e14) === 46))) break
          _e14 += 1
          const _s16 = _e14
          while (_e14 < input.length && ((input.charCodeAt(_e14) >= 48 && input.charCodeAt(_e14) <= 57))) _e14++
          if (_e14 === _s16) break
          _ok15 = true
        } while (false)
        if (!_ok15) _e14 = _e7
        if (_ok15) _e7 = _e14
        let _e17 = _e7
        let _ok18 = false
        do {
          if (!(_e17 < input.length && (input.charCodeAt(_e17) === 101 || input.charCodeAt(_e17) === 69))) break
          _e17++
          if (_e17 < input.length && (input.charCodeAt(_e17) === 43 || input.charCodeAt(_e17) === 45)) _e17++
          const _s19 = _e17
          while (_e17 < input.length && ((input.charCodeAt(_e17) >= 48 && input.charCodeAt(_e17) <= 57))) _e17++
          if (_e17 === _s19) break
          _ok18 = true
        } while (false)
        if (!_ok18) _e17 = _e7
        if (_ok18) _e7 = _e17
        _ok8 = true
      } while (false)
      if (!_ok8) _e7 = _pos
      if (!(_ok8)) {
        { _ctx._fe = _pos; _ctx._fx = _fx1; break _pfail }
      }
      const _v6 = input.slice(_pos, _e7)
      const _mapped20 = _mf[1](_v6, { start: _pos, end: _e7 })
      _chv1 = _mapped20
      _che2 = _e7
    }
    else if (_code0 === 123) {
      let _lbl21ok = false, _lbl21v, _lbl21e = _pos
      _lbl21: {
        const _start49 = _pos
        let _cur50 = _pos
        if (_cur50 >= input.length || input.charCodeAt(_cur50) !== 123) {
          { _ctx._fe = _cur50; _ctx._fx = _fx2; break _lbl21 }
        }
        const _v51 = "{"
        _cur50 = _cur50 + 1
        _cur50 = _tf0(input, _cur50, _ctx)
        let _lbl54ok = false, _lbl54v, _lbl54e = _cur50
        _lbl54: {
          const _arr55 = []
          let _cur56 = _cur50
          let _lbl57ok = false, _lbl57v, _lbl57e = _cur50
          _lbl57: {
            const _pfv58 = _pf1(input, _cur50, _ctx)
            if (_pfv58 === _pfFail) {
              break _lbl57
            }
            const _pfe59 = _pfEnd
            _lbl57v = _pfv58; _lbl57e = _pfe59; _lbl57ok = true
          }
          if (_lbl57ok) {
            _arr55.push(_lbl57v)
            _cur56 = _lbl57e
            while (_cur56 < input.length) {
              const _sp60 = _tf0(input, _cur56, _ctx)
              let _lbl61ok = false, _lbl61v, _lbl61e = _sp60
              _lbl61: {
                if (_sp60 >= input.length || input.charCodeAt(_sp60) !== 44) {
                  break _lbl61
                }
                const _v62 = ","
                _lbl61v = _v62; _lbl61e = _sp60 + 1; _lbl61ok = true
              }
              if (!_lbl61ok) break
              const _np63 = _tf0(input, _lbl61e, _ctx)
              let _lbl64ok = false, _lbl64v, _lbl64e = _np63
              _lbl64: {
                const _pfv65 = _pf1(input, _np63, _ctx)
                if (_pfv65 === _pfFail) {
                  break _lbl64
                }
                const _pfe66 = _pfEnd
                _lbl64v = _pfv65; _lbl64e = _pfe66; _lbl64ok = true
              }
              if (!_lbl64ok) break
              _arr55.push(_lbl64v)
              _cur56 = _lbl64e
            }
          }
          _lbl54v = _arr55; _lbl54e = _cur56; _lbl54ok = true
        }
        const _opt52 = _lbl54ok ? _lbl54v : null
        const _opte53 = _lbl54ok ? _lbl54e : _cur50
        _cur50 = _opte53
        _cur50 = _tf0(input, _cur50, _ctx)
        if (_cur50 >= input.length || input.charCodeAt(_cur50) !== 125) {
          { _ctx._fe = _cur50; _ctx._fx = _fx4; break _lbl21 }
        }
        const _v67 = "}"
        _cur50 = _cur50 + 1
        const _arr68 = [_v51, _opt52, _v67]
        const _mapped69 = _mf[2](_arr68, { start: _pos, end: _cur50 })
        _lbl21v = _mapped69; _lbl21e = _cur50; _lbl21ok = true
      }
      if (!_lbl21ok) {
        { _ctx._fe = _pos; _ctx._fx = _ctx._fx; break _pfail }
      }
      _chv1 = _lbl21v
      _che2 = _lbl21e
    }
    else if (_code0 === 91) {
      let _lbl70ok = false, _lbl70v, _lbl70e = _pos
      _lbl70: {
        const _start90 = _pos
        let _cur91 = _pos
        if (_cur91 >= input.length || input.charCodeAt(_cur91) !== 91) {
          { _ctx._fe = _cur91; _ctx._fx = _fx5; break _lbl70 }
        }
        const _v92 = "["
        _cur91 = _cur91 + 1
        _cur91 = _tf0(input, _cur91, _ctx)
        let _lbl95ok = false, _lbl95v, _lbl95e = _cur91
        _lbl95: {
          const _arr96 = []
          let _cur97 = _cur91
          let _lbl98ok = false, _lbl98v, _lbl98e = _cur91
          _lbl98: {
            const _pfv99 = _pf0(input, _cur91, _ctx)
            if (_pfv99 === _pfFail) {
              break _lbl98
            }
            const _pfe100 = _pfEnd
            _lbl98v = _pfv99; _lbl98e = _pfe100; _lbl98ok = true
          }
          if (_lbl98ok) {
            _arr96.push(_lbl98v)
            _cur97 = _lbl98e
            while (_cur97 < input.length) {
              const _sp101 = _tf0(input, _cur97, _ctx)
              let _lbl102ok = false, _lbl102v, _lbl102e = _sp101
              _lbl102: {
                if (_sp101 >= input.length || input.charCodeAt(_sp101) !== 44) {
                  break _lbl102
                }
                const _v103 = ","
                _lbl102v = _v103; _lbl102e = _sp101 + 1; _lbl102ok = true
              }
              if (!_lbl102ok) break
              const _np104 = _tf0(input, _lbl102e, _ctx)
              let _lbl105ok = false, _lbl105v, _lbl105e = _np104
              _lbl105: {
                const _pfv106 = _pf0(input, _np104, _ctx)
                if (_pfv106 === _pfFail) {
                  break _lbl105
                }
                const _pfe107 = _pfEnd
                _lbl105v = _pfv106; _lbl105e = _pfe107; _lbl105ok = true
              }
              if (!_lbl105ok) break
              _arr96.push(_lbl105v)
              _cur97 = _lbl105e
            }
          }
          _lbl95v = _arr96; _lbl95e = _cur97; _lbl95ok = true
        }
        const _opt93 = _lbl95ok ? _lbl95v : null
        const _opte94 = _lbl95ok ? _lbl95e : _cur91
        _cur91 = _opte94
        _cur91 = _tf0(input, _cur91, _ctx)
        if (_cur91 >= input.length || input.charCodeAt(_cur91) !== 93) {
          { _ctx._fe = _cur91; _ctx._fx = _fx6; break _lbl70 }
        }
        const _v108 = "]"
        _cur91 = _cur91 + 1
        const _arr109 = [_v92, _opt93, _v108]
        const _mapped110 = _mf[3](_arr109, { start: _pos, end: _cur91 })
        _lbl70v = _mapped110; _lbl70e = _cur91; _lbl70ok = true
      }
      if (!_lbl70ok) {
        { _ctx._fe = _pos; _ctx._fx = _ctx._fx; break _pfail }
      }
      _chv1 = _lbl70v
      _che2 = _lbl70e
    }
    else if (_code0 === 116) {
      if (_pos + 4 > input.length || input.charCodeAt(_pos) !== 116 || input.charCodeAt(_pos + 1) !== 114 || input.charCodeAt(_pos + 2) !== 117 || input.charCodeAt(_pos + 3) !== 101) {
        { _ctx._fe = _pos; _ctx._fx = _fx7; break _pfail }
      }
      const _v111 = "true"
      const _mapped112 = _mf[4](_v111, { start: _pos, end: _pos + 4 })
      _chv1 = _mapped112
      _che2 = _pos + 4
    }
    else if (_code0 === 102) {
      if (_pos + 5 > input.length || input.charCodeAt(_pos) !== 102 || input.charCodeAt(_pos + 1) !== 97 || input.charCodeAt(_pos + 2) !== 108 || input.charCodeAt(_pos + 3) !== 115 || input.charCodeAt(_pos + 4) !== 101) {
        { _ctx._fe = _pos; _ctx._fx = _fx8; break _pfail }
      }
      const _v113 = "false"
      const _mapped114 = _mf[5](_v113, { start: _pos, end: _pos + 5 })
      _chv1 = _mapped114
      _che2 = _pos + 5
    }
    else if (_code0 === 110) {
      if (_pos + 4 > input.length || input.charCodeAt(_pos) !== 110 || input.charCodeAt(_pos + 1) !== 117 || input.charCodeAt(_pos + 2) !== 108 || input.charCodeAt(_pos + 3) !== 108) {
        { _ctx._fe = _pos; _ctx._fx = _fx9; break _pfail }
      }
      const _v115 = "null"
      const _mapped116 = _mf[6](_v115, { start: _pos, end: _pos + 4 })
      _chv1 = _mapped116
      _che2 = _pos + 4
    }
    else {
      { _ctx._fe = _pos; _ctx._fx = _fx10; break _pfail }
    }
    _pfEnd = _che2
    return _chv1
  }
  return _pfFail
}
const _mf = [function(_v,_s){return undefined}, function(_v,_s){return undefined}, function(_v,_s){return undefined}, function(_v,_s){return undefined}, function(_v,_s){return undefined}, function(_v,_s){return undefined}, function(_v,_s){return undefined}]

function _parse(input, _pos, _rp, _mf, _build, _ctx) {
  let pos = _pos
  const _pfv117 = _pf0(input, _pos, _ctx)
  if (_pfv117 === _pfFail) {
    return { ok: false, expected: [..._ctx._fx], span: { start: _ctx._fe, end: _ctx._fe } }
  }
  const _pfe118 = _pfEnd
  return { ok: true, value: _pfv117, span: { start: _pos, end: _pfe118 } }
}

window.parse = function parse_json_parseman_compiled(input) {
  const result = _parse(input, 0, [], _mf, [], { trackLines: false })
  if (!result.ok) {
    throw new SyntaxError(
      'JSON parse error at offset ' + result.span.start +
      ': expected ' + result.expected.join(' or '),
    )
  }
  return result
}
