// Generated by Parséman 0.20.0 (interpreted) — do not edit by hand.
// Source: examples/json/chevrotain-bench.ts + scripts/chevrotain-bench-interpreter-entry.ts
// Rebuild: pnpm build:chevrotain-bench

"use strict";
(() => {
  // src/combinators/first-set.ts
  function union(a, b) {
    if (a.kind === "any" || b.kind === "any") return { kind: "any" };
    if (a.kind === "empty") return b;
    if (b.kind === "empty") return a;
    return { kind: "ranges", ranges: mergeRanges([...a.ranges, ...b.ranges]) };
  }
  function intersects(a, b) {
    if (a.kind === "any" || b.kind === "any") return true;
    if (a.kind === "empty" || b.kind === "empty") return false;
    for (const ra of a.ranges) {
      for (const rb of b.ranges) {
        if (ra.lo <= rb.hi && rb.lo <= ra.hi) return true;
      }
    }
    return false;
  }
  function fromChar(code) {
    return { kind: "ranges", ranges: [{ lo: code, hi: code }] };
  }
  function fromRange(lo, hi) {
    return { kind: "ranges", ranges: [{ lo, hi }] };
  }
  function any() {
    return { kind: "any" };
  }
  function empty() {
    return { kind: "empty" };
  }
  function matchesEmpty(p, seen = /* @__PURE__ */ new Set()) {
    if (seen.has(p)) return true;
    seen.add(p);
    const me = (c) => matchesEmpty(c, seen);
    const d = p._def;
    switch (d.tag) {
      case "literal":
        return d.value.length === 0;
      case "keywords":
        return false;
      case "regex":
        try {
          const m = new RegExp(d.source).exec("");
          return m != null && m[0] === "";
        } catch {
          return true;
        }
      case "many":
      case "optional":
      case "not":
        return true;
      // zero repetitions / absent / lookahead
      case "oneOrMore":
        return me(d.parser);
      case "sequence":
        return d.parsers.every(me);
      case "choice":
        return d.parsers.some(me);
      case "transform":
      case "label":
      case "trivia":
      case "token":
      case "expect":
      case "withCtx":
      case "node":
      case "grammar":
      case "recover":
        return me(d.parser);
      case "skip":
        return me(d.main);
      case "lazy":
        try {
          return me(d.thunk());
        } catch {
          return true;
        }
      default:
        return true;
    }
  }
  function sequenceFirstSet(parsers) {
    let fs = empty();
    for (const p of parsers) {
      fs = union(fs, p._meta.firstSet);
      if (!matchesEmpty(p)) return fs;
    }
    return fs;
  }
  function mergeRanges(ranges) {
    if (ranges.length === 0) return [];
    const sorted = [...ranges].sort((a, b) => a.lo - b.lo);
    const out = [{ lo: sorted[0].lo, hi: sorted[0].hi }];
    for (let i = 1; i < sorted.length; i++) {
      const top = out[out.length - 1];
      const cur = sorted[i];
      if (cur.lo <= top.hi + 1) {
        if (cur.hi > top.hi) top.hi = cur.hi;
      } else {
        out.push({ lo: cur.lo, hi: cur.hi });
      }
    }
    return out;
  }

  // src/combinators/probe.ts
  function failAt(ctx, expected, pos) {
    const r = { ok: false, expected, span: { start: pos, end: pos } };
    const probe = ctx._probe;
    if (probe !== void 0 && pos <= probe.offset) {
      const best = probe.best;
      if (best === null || pos > best.span.start) {
        probe.best = r;
      } else if (pos === best.span.start) {
        probe.best = { ...best, expected: [...best.expected, ...expected] };
      }
    }
    return r;
  }

  // src/cst/capture-buffer.ts
  function cstCaptureActive(ctx) {
    return ctx._cstBuf !== void 0 || ctx._cstLeaves !== void 0;
  }
  function pushCstLeaf(ctx, leaf) {
    pushCstChild(ctx, leaf, leaf);
  }
  function pushCstChild(ctx, built, rawEntry) {
    const b = ctx._cstBuf;
    if (b) {
      if (b.ch) b.ch.push(built);
      else if (b.single !== void 0) {
        b.ch = [b.single, built];
        b.single = void 0;
      } else b.single = built;
      if (b.raw) b.raw.push(rawEntry);
      else if (b.rawSingle !== void 0) {
        b.raw = [b.rawSingle, rawEntry];
        b.rawSingle = void 0;
      } else b.rawSingle = rawEntry;
      return;
    }
    if (ctx._cstChildren) ctx._cstChildren.push(built);
    else if (ctx._cstLeaves) ctx._cstLeaves.push(built);
    if (ctx._cstRawChildren) ctx._cstRawChildren.push(rawEntry);
  }
  function cstRawLen(ctx) {
    const b = ctx._cstBuf;
    if (b) {
      if (b.raw) return b.raw.length;
      return b.rawSingle !== void 0 ? 1 : 0;
    }
    return ctx._cstRawChildren?.length ?? 0;
  }
  function cstLeavesLen(ctx) {
    const b = ctx._cstBuf;
    if (b) {
      if (b.ch) return b.ch.length;
      return b.single !== void 0 ? 1 : 0;
    }
    return ctx._cstLeaves?.length ?? 0;
  }
  function cstTlLen(ctx) {
    const b = ctx._cstBuf;
    if (b) return b.tl?.length ?? 0;
    return ctx._cstTriviaLog?.length ?? 0;
  }
  function saveCstMark(ctx) {
    return {
      raw: cstRawLen(ctx),
      tlog: cstTlLen(ctx),
      leaves: cstLeavesLen(ctx),
      fields: ctx._fields?.length ?? 0
    };
  }
  function rollbackBufList(b, keyMulti, keySingle, len) {
    const arr = b[keyMulti];
    if (arr) {
      if (len === 0) b[keyMulti] = void 0;
      else if (len === 1) {
        b[keySingle] = arr[0];
        b[keyMulti] = void 0;
      } else arr.length = len;
      return;
    }
    if (len === 0) b[keySingle] = void 0;
  }
  function rollbackCstCapture(ctx, mark) {
    const b = ctx._cstBuf;
    if (b) {
      rollbackBufList(b, "raw", "rawSingle", mark.raw);
      rollbackBufList(b, "ch", "single", mark.leaves);
      if (b.tl) {
        if (mark.tlog === 0) b.tl = void 0;
        else b.tl.length = mark.tlog;
      }
      if (ctx._fields) ctx._fields.length = mark.fields;
      return;
    }
    if (ctx._cstRawChildren) ctx._cstRawChildren.length = mark.raw;
    if (ctx._cstTriviaLog) ctx._cstTriviaLog.length = mark.tlog;
    if (ctx._cstLeaves) ctx._cstLeaves.length = mark.leaves;
    if (ctx._fields) ctx._fields.length = mark.fields;
  }
  function pushCstTriviaEntry(ctx, start, end, kindIndex) {
    const insertIdx = cstRawLen(ctx);
    const b = ctx._cstBuf;
    const withKind = ctx.triviaKindLabels !== void 0 && kindIndex !== void 0;
    if (b) {
      if (!b.tl) {
        b.tl = withKind ? [start, end, insertIdx, kindIndex] : [start, end, insertIdx];
      } else if (withKind) {
        b.tl.push(start, end, insertIdx, kindIndex);
      } else {
        b.tl.push(start, end, insertIdx);
      }
      return;
    }
    if (ctx._cstTriviaLog) {
      if (withKind) ctx._cstTriviaLog.push(start, end, insertIdx, kindIndex);
      else ctx._cstTriviaLog.push(start, end, insertIdx);
    }
  }
  function pushTriviaLogEntry(ctx, start, end, kindIndex) {
    if (!ctx._triviaLog) return;
    if (ctx.triviaKindLabels !== void 0 && kindIndex !== void 0) {
      ctx._triviaLog.push(start, end, kindIndex);
    } else {
      ctx._triviaLog.push(start, end);
    }
  }

  // src/combinators/literal.ts
  function asciiFoldEq(a, b) {
    if (a.length !== b.length) return false;
    for (let i = 0; i < a.length; i++) {
      let ca = a.charCodeAt(i);
      let cb = b.charCodeAt(i);
      if (ca >= 65 && ca <= 90) ca += 32;
      if (cb >= 65 && cb <= 90) cb += 32;
      if (ca !== cb) return false;
    }
    return true;
  }
  function literal(value, opts = {}) {
    const caseInsensitive = opts.caseInsensitive ?? false;
    const firstSet2 = value.length > 0 ? fromChar(value.codePointAt(0)) : empty();
    const meta = {
      firstSet: firstSet2,
      canMatchNewline: value.includes("\n"),
      isTrivia: false
    };
    if (caseInsensitive) {
      const upper = value.toUpperCase();
      const lower = value.toLowerCase();
      const firstUpper = upper.codePointAt(0);
      const firstLower = lower.codePointAt(0);
      meta.firstSet = firstLower !== void 0 && firstUpper !== void 0 ? firstLower === firstUpper ? { kind: "ranges", ranges: [{ lo: firstLower, hi: firstLower }] } : { kind: "ranges", ranges: [
        { lo: firstLower, hi: firstLower },
        { lo: firstUpper, hi: firstUpper }
      ] } : firstSet2;
    }
    return {
      _tag: "literal",
      _meta: meta,
      _def: { tag: "literal", value, caseInsensitive },
      parse(input, pos, ctx) {
        const end = pos + value.length;
        if (end > input.length) {
          return failAt(ctx, [JSON.stringify(value)], pos);
        }
        const matchedValue = caseInsensitive ? input.slice(pos, end) : value;
        if (caseInsensitive ? asciiFoldEq(matchedValue, value) : input.startsWith(value, pos)) {
          const span = { start: pos, end };
          const leaf = { _tag: "leaf", value: matchedValue, span };
          if (cstCaptureActive(ctx)) pushCstLeaf(ctx, leaf);
          return { ok: true, value: matchedValue, span };
        }
        return failAt(ctx, [JSON.stringify(value)], pos);
      }
    };
  }

  // src/regex/classes.ts
  var CLASS_ESCAPES = { t: 9, n: 10, r: 13, f: 12, v: 11, "0": 0 };
  var SPACE_RANGES = [
    [9, 13],
    [32, 32],
    [160, 160],
    [5760, 5760],
    [8192, 8202],
    [8232, 8232],
    [8233, 8233],
    [8239, 8239],
    [8287, 8287],
    [12288, 12288],
    [65279, 65279]
  ];
  function shorthandRanges(ch) {
    if (ch === "d") return [[48, 57]];
    if (ch === "s") return SPACE_RANGES;
    return [[48, 57], [65, 90], [97, 122], [95, 95]];
  }
  function readUnicodeEscape(body, i) {
    if (body[i] !== "\\" || body[i + 1] !== "u") return null;
    const hex = body.slice(i + 2, i + 6);
    if (!/^[0-9a-fA-F]{4}$/.test(hex)) return null;
    return { cp: Number.parseInt(hex, 16), next: i + 6 };
  }
  function parseClassRanges(body) {
    const ranges = [];
    let i = 0;
    const readAtom = () => {
      const ch = body[i];
      if (ch === void 0) return null;
      if (ch === "\\") {
        const uni = readUnicodeEscape(body, i);
        if (uni) {
          i = uni.next;
          return { cp: uni.cp };
        }
        const e = body[i + 1];
        if (e === void 0) return null;
        i += 2;
        if (e in CLASS_ESCAPES) return { cp: CLASS_ESCAPES[e] };
        if (e === "d" || e === "w" || e === "s") return { set: shorthandRanges(e) };
        if (e >= "a" && e <= "z" || e >= "A" && e <= "Z") return null;
        return { cp: e.codePointAt(0) };
      }
      i += ch.length;
      return { cp: ch.codePointAt(0) };
    };
    while (i < body.length) {
      const lo = readAtom();
      if (lo === null) return null;
      if ("set" in lo) {
        ranges.push(...lo.set);
        continue;
      }
      if (body[i] === "-" && body[i + 1] !== void 0 && body[i + 1] !== "]") {
        i += 1;
        const hi = readAtom();
        if (hi === null || "set" in hi) return null;
        ranges.push([lo.cp, hi.cp]);
      } else {
        ranges.push([lo.cp, lo.cp]);
      }
    }
    return ranges.length ? ranges : null;
  }

  // src/combinators/regex.ts
  var firstSetAnalyzer = null;
  function registerRegexAnalyzer(analyzer) {
    firstSetAnalyzer = analyzer;
  }
  var permissiveFirstSet = () => ({ firstSet: any(), canMatchNewline: true });
  var SCAN_BAIL_AT = 64;
  function inRanges(cp, ranges) {
    for (let i = 0; i < ranges.length; i++) {
      const [lo, hi] = ranges[i];
      if (cp >= lo && cp <= hi) return true;
    }
    return false;
  }
  function readClassRanges(body) {
    if (body.startsWith("^")) return null;
    return parseClassRanges(body);
  }
  function shortScanner(source, flags) {
    if (/[imsuvy]/.test(flags)) return null;
    let ranges = null;
    let quant = "";
    if (source[0] === "[") {
      let end = 1;
      while (end < source.length && source[end] !== "]") {
        if (source[end] === "\\") end += 2;
        else end++;
      }
      if (source[end] !== "]") return null;
      ranges = readClassRanges(source.slice(1, end));
      quant = source.slice(end + 1);
    } else if (source[0] === "\\" && (source[1] === "d" || source[1] === "w" || source[1] === "s")) {
      ranges = shorthandRanges(source[1]);
      quant = source.slice(2);
    }
    if (!ranges || quant !== "+" && quant !== "*") return null;
    const minOne = quant === "+";
    return (input, pos) => {
      let end = pos;
      while (end < input.length && inRanges(input.charCodeAt(end), ranges)) {
        end++;
        if (end - pos >= SCAN_BAIL_AT) return void 0;
      }
      return minOne && end === pos ? null : end;
    };
  }
  function regex(pattern, flags = "") {
    const source = typeof pattern === "string" ? pattern : pattern.source;
    const resolvedFlags = typeof pattern === "string" ? flags : pattern.flags;
    const anchored = new RegExp(source, "y" + resolvedFlags.replace(/[gy]/g, ""));
    const scan = shortScanner(source, resolvedFlags);
    const { firstSet: firstSet2, canMatchNewline } = (firstSetAnalyzer ?? permissiveFirstSet)(source);
    const meta = { firstSet: firstSet2, canMatchNewline, isTrivia: false };
    return {
      _tag: "regex",
      _meta: meta,
      _def: { tag: "regex", source, flags: resolvedFlags },
      parse(input, pos, ctx) {
        const scanEnd = scan?.(input, pos);
        if (scanEnd !== void 0) {
          if (scanEnd === null) return failAt(ctx, [`/${source}/`], pos);
          const value = input.slice(pos, scanEnd);
          const span2 = { start: pos, end: scanEnd };
          const leaf2 = { _tag: "leaf", value, span: span2 };
          if (cstCaptureActive(ctx)) pushCstLeaf(ctx, leaf2);
          return { ok: true, value, span: span2 };
        }
        anchored.lastIndex = pos;
        const m = anchored.exec(input);
        if (m === null) {
          return failAt(ctx, [`/${source}/`], pos);
        }
        const span = { start: pos, end: pos + m[0].length };
        const leaf = { _tag: "leaf", value: m[0], span };
        if (cstCaptureActive(ctx)) pushCstLeaf(ctx, leaf);
        return { ok: true, value: m[0], span };
      }
    };
  }

  // src/regex/first-set.ts
  var ANY = { t: "any" };
  var EMPTY = { t: "empty" };
  function charNode(set, nl) {
    return { t: "char", set, nl };
  }
  function rangesToSet(ranges) {
    let fs = empty();
    for (const [lo, hi] of ranges) fs = union(fs, fromRange(lo, hi));
    return fs;
  }
  function rangesHaveNewline(ranges) {
    return ranges.some(([lo, hi]) => lo <= 10 && 10 <= hi);
  }
  var BAIL = /* @__PURE__ */ Symbol("regex-bail");
  function parseRegex(src) {
    let i = 0;
    const parseAlt = () => {
      const arms = [parseSeq()];
      while (src[i] === "|") {
        i++;
        arms.push(parseSeq());
      }
      return arms.length === 1 ? arms[0] : { t: "alt", arms };
    };
    const parseSeq = () => {
      const parts = [];
      while (i < src.length) {
        const ch = src[i];
        if (ch === "|" || ch === ")") break;
        parts.push(parseQuantified());
      }
      if (parts.length === 0) return EMPTY;
      return parts.length === 1 ? parts[0] : { t: "seq", parts };
    };
    const parseQuantified = () => {
      const atom = parseAtom();
      const ch = src[i];
      let min = null;
      if (ch === "*") {
        min = 0;
        i++;
      } else if (ch === "+") {
        min = 1;
        i++;
      } else if (ch === "?") {
        min = 0;
        i++;
      } else if (ch === "{") {
        min = parseBraceQuantifier();
      }
      if (min === null) return atom;
      if (src[i] === "?") i++;
      return { t: "rep", node: atom, min };
    };
    const parseBraceQuantifier = () => {
      const close = src.indexOf("}", i);
      if (close === -1) return null;
      const m = /^(\d+)(?:,(\d*))?$/.exec(src.slice(i + 1, close));
      if (!m) return null;
      i = close + 1;
      return Number.parseInt(m[1], 10);
    };
    const parseAtom = () => {
      const ch = src[i];
      switch (ch) {
        case "(":
          return parseGroup();
        case "[":
          return parseClass();
        case ".":
          i++;
          return charNode(any(), false);
        // `.` matches any char except line terminators
        case "\\":
          return parseEscape();
        case "^":
        case "$":
          i++;
          return EMPTY;
        // anchors are zero-width
        case "{":
          i++;
          return charNode(fromRange(123, 123), false);
        // a `{` with nothing to quantify is a literal brace
        default:
          i += ch.length;
          return charNode(fromRange(ch.codePointAt(0), ch.codePointAt(0)), ch === "\n");
      }
    };
    const parseGroup = () => {
      i++;
      let lookaround = false;
      if (src[i] === "?") {
        const c1 = src[i + 1];
        if (c1 === ":") i += 2;
        else if (c1 === "=" || c1 === "!") {
          i += 2;
          lookaround = true;
        } else if (c1 === "<") {
          const c2 = src[i + 2];
          if (c2 === "=" || c2 === "!") {
            i += 3;
            lookaround = true;
          } else {
            const gt = src.indexOf(">", i);
            if (gt === -1) throw BAIL;
            i = gt + 1;
          }
        } else throw BAIL;
      }
      const inner = parseAlt();
      if (src[i] !== ")") throw BAIL;
      i++;
      return lookaround ? EMPTY : inner;
    };
    const parseClass = () => {
      let k = i + 1;
      const negated = src[k] === "^";
      if (negated) k++;
      let body = "";
      while (k < src.length && src[k] !== "]") {
        if (src[k] === "\\") {
          body += src[k] + (src[k + 1] ?? "");
          k += 2;
        } else {
          body += src[k];
          k++;
        }
      }
      if (src[k] !== "]") throw BAIL;
      i = k + 1;
      if (negated) return charNode(any(), true);
      const ranges = parseClassRanges(body);
      if (!ranges) return charNode(any(), true);
      return charNode(rangesToSet(ranges), rangesHaveNewline(ranges));
    };
    const parseEscape = () => {
      const e = src[i + 1];
      if (e === void 0) throw BAIL;
      if (e === "u" && /^[0-9a-fA-F]{4}$/.test(src.slice(i + 2, i + 6))) {
        const cp = Number.parseInt(src.slice(i + 2, i + 6), 16);
        i += 6;
        return charNode(fromRange(cp, cp), cp === 10);
      }
      if (e === "x" && /^[0-9a-fA-F]{2}$/.test(src.slice(i + 2, i + 4))) {
        const cp = Number.parseInt(src.slice(i + 2, i + 4), 16);
        i += 4;
        return charNode(fromRange(cp, cp), cp === 10);
      }
      i += 2;
      switch (e) {
        case "d":
          return charNode(rangesToSet(shorthandRanges("d")), false);
        case "w":
          return charNode(rangesToSet(shorthandRanges("w")), false);
        case "s":
          return charNode(rangesToSet(shorthandRanges("s")), true);
        case "D":
        case "W":
        case "S":
          return charNode(any(), true);
        // negated shorthand → widen
        case "b":
        case "B":
          return EMPTY;
        // word boundary: zero-width
        case "n":
          return charNode(fromRange(10, 10), true);
        case "r":
          return charNode(fromRange(13, 13), false);
        case "t":
          return charNode(fromRange(9, 9), false);
        case "f":
          return charNode(fromRange(12, 12), false);
        case "v":
          return charNode(fromRange(11, 11), false);
        case "0":
          return charNode(fromRange(0, 0), false);
        default:
          if (e >= "1" && e <= "9") return ANY;
          return charNode(fromRange(e.codePointAt(0), e.codePointAt(0)), e === "\n");
      }
    };
    const node2 = parseAlt();
    if (i < src.length) throw BAIL;
    return node2;
  }
  function nullable(n) {
    switch (n.t) {
      case "char":
        return false;
      case "any":
        return true;
      case "empty":
        return true;
      case "seq":
        return n.parts.every(nullable);
      case "alt":
        return n.arms.some(nullable);
      case "rep":
        return n.min === 0 || nullable(n.node);
    }
  }
  function firstSet(n) {
    switch (n.t) {
      case "char":
        return n.set;
      case "any":
        return any();
      case "empty":
        return empty();
      case "rep":
        return firstSet(n.node);
      case "alt": {
        let fs = empty();
        for (const arm of n.arms) fs = union(fs, firstSet(arm));
        return fs;
      }
      case "seq": {
        let fs = empty();
        for (const part of n.parts) {
          fs = union(fs, firstSet(part));
          if (!nullable(part)) break;
        }
        return fs;
      }
    }
  }
  function firstCanBeNewline(n) {
    switch (n.t) {
      case "char":
        return n.nl;
      case "any":
        return true;
      case "empty":
        return false;
      case "rep":
        return firstCanBeNewline(n.node);
      case "alt":
        return n.arms.some(firstCanBeNewline);
      case "seq": {
        for (const part of n.parts) {
          if (firstCanBeNewline(part)) return true;
          if (!nullable(part)) break;
        }
        return false;
      }
    }
  }
  function firstSetFromRegex(source) {
    let ast;
    try {
      ast = parseRegex(source);
    } catch {
      return { firstSet: any(), canMatchNewline: true };
    }
    if (nullable(ast)) return { firstSet: any(), canMatchNewline: true };
    return { firstSet: firstSet(ast), canMatchNewline: firstCanBeNewline(ast) };
  }

  // src/combinators/choice.ts
  function choice(...args) {
    const parsers = args.map((a) => "gate" in a ? a.combinator : a);
    const gates = args.map((a) => "gate" in a ? a.gate : null);
    const hasGates = gates.some((g) => g !== null);
    const disjoint = !hasGates && areDisjoint(parsers.map((p) => p._meta.firstSet));
    let combined = { kind: "empty" };
    for (const p of parsers) combined = union(combined, p._meta.firstSet);
    const meta = {
      firstSet: combined,
      canMatchNewline: parsers.some((p) => p._meta.canMatchNewline),
      isTrivia: false,
      disjoint
    };
    const strategy = disjoint || hasGates ? null : detectStrategy(parsers);
    const autoNot = !disjoint && !hasGates && strategy?.tag === "firstMatch" ? computeAutoNot(parsers) : parsers.map(() => null);
    let greedyLitMap = null;
    let sortedParsers = null;
    const asciiDispatch = disjoint ? buildAsciiDispatch(parsers) : null;
    if (strategy?.tag === "greedyClassify") {
      greedyLitMap = /* @__PURE__ */ new Map();
      for (let i = 0; i < parsers.length; i++) {
        if (i === strategy.superIndex) continue;
        const litVal = getCoreLiteralValue(parsers[i]);
        if (litVal !== null) greedyLitMap.set(litVal, i);
      }
    } else if (strategy?.tag === "literalsLongestFirst") {
      sortedParsers = strategy.sortedIndices.map((i) => parsers[i]);
    }
    return {
      _tag: "choice",
      _meta: meta,
      _def: {
        tag: "choice",
        parsers,
        gates,
        disjoint,
        strategy: strategy ?? { tag: "firstMatch" },
        autoNot
      },
      parse(input, pos, ctx) {
        const expected = [];
        if (disjoint && pos < input.length) {
          const code = input.codePointAt(pos);
          let parser2 = code < 128 ? asciiDispatch?.[code] ?? null : null;
          if (!parser2) {
            for (const p of parsers) {
              if (inFirstSet(code, p._meta.firstSet)) {
                parser2 = p;
                break;
              }
            }
          }
          if (parser2) {
            const result = parser2.parse(input, pos, ctx);
            if (result.ok) return result;
            expected.push(...result.expected);
            return { ok: false, expected, span: { start: pos, end: pos } };
          }
          return {
            ok: false,
            expected: parsers.flatMap((p) => {
              const r = p.parse(input, pos, ctx);
              return r.ok ? [] : r.expected;
            }),
            span: { start: pos, end: pos }
          };
        }
        if (strategy?.tag === "greedyClassify") {
          const superResult = parsers[strategy.superIndex].parse(input, pos, ctx);
          if (!superResult.ok) return superResult;
          const end = superResult.span.end;
          const litIdx = greedyLitMap.get(input.slice(pos, end));
          if (litIdx !== void 0) {
            const litVal = getCoreLiteralValue(parsers[litIdx]);
            const value = applyTransforms(parsers[litIdx], litVal, { start: pos, end });
            return { ok: true, value, span: { start: pos, end } };
          }
          return superResult;
        }
        if (strategy?.tag === "literalsLongestFirst") {
          for (const p of sortedParsers) {
            const r = p.parse(input, pos, ctx);
            if (r.ok) return r;
            expected.push(...r.expected);
          }
          return { ok: false, expected, span: { start: pos, end: pos } };
        }
        for (let i = 0; i < parsers.length; i++) {
          if (gates[i] && !gates[i](ctx.state)) continue;
          const mark = saveCstMark(ctx);
          const logLen = ctx._triviaLog?.length;
          const result = parsers[i].parse(input, pos, ctx);
          if (!result.ok) {
            rollbackCstCapture(ctx, mark);
            if (logLen !== void 0 && ctx._triviaLog) ctx._triviaLog.length = logLen;
            expected.push(...result.expected);
            continue;
          }
          const checks = autoNot[i];
          if (checks && autoNotFires(input, result.span.end, checks)) {
            rollbackCstCapture(ctx, mark);
            if (logLen !== void 0 && ctx._triviaLog) ctx._triviaLog.length = logLen;
            continue;
          }
          return result;
        }
        return { ok: false, expected, span: { start: pos, end: pos } };
      }
    };
  }
  function detectStrategy(parsers) {
    const regexIndices = [];
    const literalIndices = [];
    for (let i = 0; i < parsers.length; i++) {
      if (getCoreRegexDef(parsers[i]) !== null) regexIndices.push(i);
      else if (getCoreLiteralValue(parsers[i]) !== null) literalIndices.push(i);
    }
    if (regexIndices.length === 1 && literalIndices.length === parsers.length - 1 && literalIndices.length > 0) {
      const superIndex = regexIndices[0];
      const regexDef = getCoreRegexDef(parsers[superIndex]);
      const flags = "y" + regexDef.flags.replace(/[gy]/g, "");
      const re = new RegExp(regexDef.source, flags);
      const allSubsumed = literalIndices.every((i) => {
        const litVal = getCoreLiteralValue(parsers[i]);
        re.lastIndex = 0;
        const m = re.exec(litVal);
        return m !== null && m[0] === litVal;
      });
      if (allSubsumed) return { tag: "greedyClassify", superIndex };
    }
    if (parsers.length === literalIndices.length) {
      const sortedIndices = [...literalIndices].sort(
        (a, b) => getCoreLiteralValue(parsers[b]).length - getCoreLiteralValue(parsers[a]).length
      );
      return { tag: "literalsLongestFirst", sortedIndices };
    }
    return { tag: "firstMatch" };
  }
  function computeAutoNot(parsers) {
    return parsers.map((p, i) => {
      const litVal = getCoreLiteralValue(p);
      if (litVal === null) return null;
      const checks = [];
      for (let j = i + 1; j < parsers.length; j++) {
        const other = parsers[j];
        const otherLit = getCoreLiteralValue(other);
        if (otherLit !== null && otherLit.startsWith(litVal) && otherLit.length > litVal.length) {
          checks.push({ kind: "startsWith", value: otherLit.slice(litVal.length) });
          continue;
        }
        const regexDef = getCoreRegexDef(other);
        if (regexDef !== null) {
          const contSet = continuationFirstSet(litVal, regexDef.source, regexDef.flags);
          if (contSet !== null) checks.push({ kind: "firstSet", set: contSet });
        }
      }
      return checks.length > 0 ? checks : null;
    });
  }
  function autoNotFires(input, end, checks) {
    for (const check of checks) {
      if (check.kind === "firstSet") {
        const code = end < input.length ? input.codePointAt(end) ?? -1 : -1;
        if (inFirstSet(code, check.set)) return true;
      } else {
        if (input.startsWith(check.value, end)) return true;
      }
    }
    return false;
  }
  function getCoreLiteralValue(p) {
    const def = p._def;
    if (def.tag === "literal" && !def.caseInsensitive) return def.value;
    if (def.tag === "transform") return getCoreLiteralValue(def.parser);
    return null;
  }
  function getCoreRegexDef(p) {
    const def = p._def;
    if (def.tag === "regex") return { source: def.source, flags: def.flags };
    if (def.tag === "transform") return getCoreRegexDef(def.parser);
    if (def.tag === "label") return getCoreRegexDef(def.parser);
    return null;
  }
  function applyTransforms(p, value, span) {
    const def = p._def;
    if (def.tag === "transform") {
      const inner = applyTransforms(def.parser, value, span);
      return def.fn(inner, span);
    }
    return value;
  }
  function continuationFirstSet(lit, source, flags) {
    const re = new RegExp(source, "y" + flags.replace(/[gy]/g, ""));
    re.lastIndex = 0;
    const base = re.exec(lit);
    if (!base || base[0] !== lit) return null;
    const contCodes = [];
    for (let code = 1; code < 128; code++) {
      re.lastIndex = 0;
      const m = re.exec(lit + String.fromCharCode(code));
      if (m && m[0].length > lit.length) contCodes.push(code);
    }
    if (contCodes.length === 0) return null;
    return codesToFirstSet(contCodes);
  }
  function codesToFirstSet(codes) {
    codes.sort((a, b) => a - b);
    const ranges = [];
    let lo = codes[0], hi = codes[0];
    for (let i = 1; i < codes.length; i++) {
      if (codes[i] === hi + 1) {
        hi = codes[i];
      } else {
        ranges.push({ lo, hi });
        lo = hi = codes[i];
      }
    }
    ranges.push({ lo, hi });
    return { kind: "ranges", ranges };
  }
  function inFirstSet(code, fs) {
    if (fs.kind === "any") return true;
    if (fs.kind === "empty") return false;
    for (const r of fs.ranges) if (code >= r.lo && code <= r.hi) return true;
    return false;
  }
  function areDisjoint(sets) {
    if (sets.some((s) => s.kind === "any")) return false;
    for (let i = 0; i < sets.length; i++)
      for (let j = i + 1; j < sets.length; j++)
        if (intersects(sets[i], sets[j])) return false;
    return true;
  }
  function buildAsciiDispatch(parsers) {
    const table = Array(128).fill(null);
    for (const parser2 of parsers) {
      const fs = parser2._meta.firstSet;
      if (fs.kind !== "ranges") continue;
      for (const { lo, hi } of fs.ranges) {
        for (let code = Math.max(0, lo); code <= Math.min(127, hi); code++) {
          table[code] = parser2;
        }
      }
    }
    return table;
  }

  // src/cst/trivia-kinds.ts
  function unwrapTrivia(p) {
    let cur = p;
    while (cur._def.tag === "trivia") cur = cur._def.parser;
    return cur;
  }
  function peelLabel(p) {
    if (p._def.tag === "label") return { label: p._def.label, parser: p._def.parser };
    return null;
  }
  function analyzeLabeledTrivia(trivia2) {
    let core = unwrapTrivia(trivia2);
    let minRepeats = 1;
    if (core._def.tag === "oneOrMore") {
      core = core._def.parser;
      minRepeats = 1;
    } else if (core._def.tag === "many") {
      core = core._def.parser;
      minRepeats = 0;
    }
    const arms = [];
    if (core._def.tag === "choice") {
      for (let i = 0; i < core._def.parsers.length; i++) {
        const peeled = peelLabel(core._def.parsers[i]);
        if (!peeled) return null;
        arms.push({ label: peeled.label, kindIndex: i, parser: peeled.parser });
      }
    } else {
      const peeled = peelLabel(core);
      if (!peeled) return null;
      arms.push({ label: peeled.label, kindIndex: 0, parser: peeled.parser });
    }
    return { labels: arms.map((a) => a.label), arms, minRepeats };
  }
  function matchArmAt(input, pos, arm) {
    const r = arm.parse(input, pos, { trackLines: false });
    if (!r.ok || r.span.end <= pos) return null;
    return { end: r.span.end };
  }
  function scanLabeledTriviaChunks(input, cur, spec) {
    const chunks = [];
    let pos = cur;
    while (pos < input.length) {
      let matched = null;
      for (const arm of spec.arms) {
        const m = matchArmAt(input, pos, arm.parser);
        if (m) {
          matched = { end: m.end, kindIndex: arm.kindIndex };
          break;
        }
      }
      if (!matched) break;
      chunks.push({ start: pos, end: matched.end, kindIndex: matched.kindIndex });
      pos = matched.end;
    }
    if (chunks.length < spec.minRepeats) {
      return { end: cur, chunks: [] };
    }
    return { end: pos, chunks };
  }
  function scanFastWsCommentsChunks(input, cur, wsKind, commentKind) {
    const chunks = [];
    let pos = cur;
    while (pos < input.length) {
      const c = input.charCodeAt(pos);
      if (c === 32 || c === 9 || c === 10 || c === 13 || c === 12) {
        const start = pos;
        pos++;
        while (pos < input.length) {
          const c2 = input.charCodeAt(pos);
          if (c2 === 32 || c2 === 9 || c2 === 10 || c2 === 13 || c2 === 12) pos++;
          else break;
        }
        chunks.push({ start, end: pos, kindIndex: wsKind });
        continue;
      }
      if (c === 47 && input.charCodeAt(pos + 1) === 42) {
        let j = pos + 2;
        while (j + 1 < input.length && !(input.charCodeAt(j) === 42 && input.charCodeAt(j + 1) === 47)) j++;
        if (j + 1 < input.length && input.charCodeAt(j) === 42 && input.charCodeAt(j + 1) === 47) {
          const start = pos;
          pos = j + 2;
          chunks.push({ start, end: pos, kindIndex: commentKind });
          continue;
        }
        break;
      }
      break;
    }
    return { end: pos, chunks };
  }
  function tryFastLabeledScan(input, cur, trivia2) {
    const spec = analyzeLabeledTrivia(trivia2);
    if (!spec || spec.arms.length !== 2) return null;
    const wsArm = spec.arms.find((a) => {
      const src = getCoreRegexDef(a.parser)?.source;
      return src != null && !src.includes("\\*");
    });
    const commentArm = spec.arms.find((a) => {
      const src = getCoreRegexDef(a.parser)?.source;
      return src != null && src.includes("\\*");
    });
    if (!wsArm || !commentArm) return null;
    const { chunks } = scanFastWsCommentsChunks(input, cur, wsArm.kindIndex, commentArm.kindIndex);
    if (chunks.length < spec.minRepeats) return { end: cur, chunks: [] };
    return scanFastWsCommentsChunks(input, cur, wsArm.kindIndex, commentArm.kindIndex);
  }
  function recordTriviaChunks(ctx, chunks) {
    const kinds = ctx.triviaKindLabels;
    for (const ch of chunks) {
      pushTriviaLogEntry(ctx, ch.start, ch.end, kinds ? ch.kindIndex : void 0);
      if (ctx.captureTrivia && (ctx._cstBuf !== void 0 || ctx._cstTriviaLog !== void 0)) {
        pushCstTriviaEntry(ctx, ch.start, ch.end, kinds ? ch.kindIndex : void 0);
      }
    }
  }

  // src/combinators/trivia-skip.ts
  var NOOP_COMMIT = () => {
  };
  var fastTriviaCache = /* @__PURE__ */ new WeakMap();
  function needsDeferredTriviaCommit(ctx) {
    return ctx._triviaLog !== void 0 || ctx._cstBuf !== void 0 || ctx._cstTriviaLog !== void 0;
  }
  function saveTriviaMark(ctx) {
    const m = saveCstMark(ctx);
    return { raw: m.raw, tlog: m.tlog, leaves: m.leaves, fields: m.fields, log: ctx._triviaLog ? ctx._triviaLog.length : 0 };
  }
  function rollbackTrivia(ctx, mark) {
    rollbackCstCapture(ctx, { raw: mark.raw, tlog: mark.tlog, leaves: mark.leaves, fields: mark.fields });
    if (ctx._triviaLog) ctx._triviaLog.length = mark.log;
  }
  function scanWithLabels(input, cur, ctx) {
    const triviaP = ctx.trivia;
    const spec = analyzeLabeledTrivia(triviaP);
    if (!spec) return { end: cur, commit: NOOP_COMMIT };
    const fast = tryFastLabeledScan(input, cur, triviaP);
    const { end, chunks } = fast ?? scanLabeledTriviaChunks(input, cur, spec);
    if (end === cur) return { end: cur, commit: NOOP_COMMIT };
    return {
      end,
      commit: () => recordTriviaChunks(ctx, chunks)
    };
  }
  function advanceTrivia(input, cur, ctx) {
    const triviaP = ctx.trivia;
    if (!triviaP) return cur;
    const fast = fastTriviaScanner(triviaP);
    if (fast) return fast(input, cur);
    if (ctx.triviaKindLabels) {
      const scan = scanWithLabels(input, cur, ctx);
      return scan.end;
    }
    const tr = triviaP.parse(input, cur, { trackLines: ctx.trackLines, state: ctx.state });
    return tr.ok && tr.span.end > cur ? tr.span.end : cur;
  }
  function scanTrivia(input, cur, ctx) {
    const triviaP = ctx.trivia;
    if (!triviaP) return { end: cur, commit: NOOP_COMMIT };
    const log = ctx._triviaLog;
    const captureTl = ctx.captureTrivia && (ctx._cstBuf !== void 0 || ctx._cstTriviaLog !== void 0);
    const fast = !ctx.triviaKindLabels ? fastTriviaScanner(triviaP) : null;
    if (fast && log === void 0 && !captureTl) {
      return { end: fast(input, cur), commit: NOOP_COMMIT };
    }
    if (ctx.triviaKindLabels && (log !== void 0 || captureTl)) {
      return scanWithLabels(input, cur, ctx);
    }
    if (log !== void 0 || captureTl) {
      const tr2 = triviaP.parse(input, cur, {
        trackLines: log !== void 0 ? false : ctx.trackLines,
        state: ctx.state
      });
      if (!tr2.ok || tr2.span.end === cur) return { end: cur, commit: NOOP_COMMIT };
      const end = tr2.span.end;
      return {
        end,
        commit: () => {
          pushTriviaLogEntry(ctx, cur, end);
          if (captureTl) pushCstTriviaEntry(ctx, cur, end);
        }
      };
    }
    const tr = triviaP.parse(input, cur, { trackLines: ctx.trackLines, state: ctx.state });
    return { end: tr.ok ? tr.span.end : cur, commit: NOOP_COMMIT };
  }
  function fastTriviaScanner(trivia2) {
    const cached = fastTriviaCache.get(trivia2);
    if (cached !== void 0) return cached;
    const scanner = buildFastTriviaScanner(trivia2);
    fastTriviaCache.set(trivia2, scanner);
    return scanner;
  }
  function buildFastTriviaScanner(trivia2) {
    const core = trivia2._def.tag === "trivia" ? trivia2._def.parser : trivia2;
    const direct = regexTriviaScanner(core);
    if (direct) return direct;
    const repeat = core._def.tag === "oneOrMore" || core._def.tag === "many" && core._def.min >= 1 ? core._def.parser : null;
    if (!repeat) return null;
    const one = regexTriviaScanner(repeat);
    if (one) return loopScanner([one]);
    if (repeat._def.tag !== "choice") return null;
    const arms = repeat._def.parsers.map(regexTriviaScanner);
    if (arms.some((s) => s === null)) return null;
    return loopScanner(arms);
  }
  function loopScanner(arms) {
    return (input, cur) => {
      let pos = cur;
      scan: while (pos < input.length) {
        for (const arm of arms) {
          const end = arm(input, pos);
          if (end > pos) {
            pos = end;
            continue scan;
          }
        }
        break;
      }
      return pos;
    };
  }
  function regexTriviaScanner(parser2) {
    if (parser2._def.tag !== "regex" || parser2._def.flags) return null;
    const ws2 = whitespaceSource(parser2._def.source);
    if (ws2) return ws2;
    return blockCommentSource(parser2._def.source) ? scanBlockComment : null;
  }
  function whitespaceSource(source) {
    const m = /^\[([ \\tnrf]+)\][*+]$/.exec(source);
    if (!m) return null;
    const chars = /* @__PURE__ */ new Set();
    for (let i = 0; i < m[1].length; i++) {
      const ch = m[1][i];
      if (ch !== "\\") {
        chars.add(ch.charCodeAt(0));
        continue;
      }
      const esc = m[1][++i];
      if (esc === "t") chars.add(9);
      else if (esc === "n") chars.add(10);
      else if (esc === "r") chars.add(13);
      else if (esc === "f") chars.add(12);
      else return null;
    }
    return (input, cur) => {
      let pos = cur;
      while (pos < input.length && chars.has(input.charCodeAt(pos))) pos++;
      return pos;
    };
  }
  function blockCommentSource(source) {
    return source === "\\/\\*(?:[^*]|\\*(?!\\/))*\\*\\/" || source === "\\/\\*[^]*?\\*\\/";
  }
  function scanBlockComment(input, cur) {
    if (input.charCodeAt(cur) !== 47 || input.charCodeAt(cur + 1) !== 42) return cur;
    const close = input.indexOf("*/", cur + 2);
    return close === -1 ? cur : close + 2;
  }

  // src/combinators/sequence.ts
  function sequence(...parsers) {
    const meta = {
      // Union through the nullable prefix — a leading optional()/many() lets a later
      // term's first char start the sequence. Just `parsers[0]` under-approximates.
      firstSet: sequenceFirstSet(parsers),
      canMatchNewline: parsers.some((p) => p._meta.canMatchNewline),
      isTrivia: false
    };
    const def = { tag: "sequence", parsers };
    return {
      _tag: "sequence",
      _meta: meta,
      _def: def,
      parse(input, pos, ctx) {
        const values = def.valueUnused ? void 0 : [];
        let cur = pos;
        for (let i = 0; i < parsers.length; i++) {
          if (ctx.trivia && i > 0) {
            let scanEnd;
            let mark = saveTriviaMark(ctx);
            if (needsDeferredTriviaCommit(ctx)) {
              const scan = scanTrivia(input, cur, ctx);
              scan.commit();
              scanEnd = scan.end;
            } else {
              scanEnd = advanceTrivia(input, cur, ctx);
            }
            const result2 = parsers[i].parse(input, scanEnd, ctx);
            if (!result2.ok) return result2;
            if (result2.span.end > scanEnd) {
              cur = result2.span.end;
            } else {
              rollbackTrivia(ctx, mark);
            }
            if (values !== void 0) values.push(result2.value);
            continue;
          }
          const result = parsers[i].parse(input, cur, ctx);
          if (!result.ok) return result;
          if (values !== void 0) values.push(result.value);
          cur = result.span.end;
        }
        return {
          ok: true,
          // eslint-disable-next-line @typescript-eslint/no-unsafe-type-assertion
          value: values ?? void 0,
          span: { start: pos, end: cur }
        };
      }
    };
  }

  // src/combinators/repeat.ts
  function optional(combinator) {
    const meta = {
      firstSet: combinator._meta.firstSet,
      canMatchNewline: combinator._meta.canMatchNewline,
      isTrivia: false
    };
    const firstSetSkippable = !matchesEmpty(combinator);
    return {
      _tag: "optional",
      _meta: meta,
      _def: { tag: "optional", parser: combinator },
      parse(input, pos, ctx) {
        if (firstSetSkippable && ctx._probe === void 0 && !startsFirstSet(combinator, input, pos)) {
          return { ok: true, value: null, span: { start: pos, end: pos } };
        }
        const mark = saveTriviaMark(ctx);
        const result = combinator.parse(input, pos, ctx);
        if (result.ok) return result;
        rollbackTrivia(ctx, mark);
        return { ok: true, value: null, span: { start: pos, end: pos } };
      }
    };
  }
  function startsFirstSet(combinator, input, pos) {
    const fs = combinator._meta.firstSet;
    if (fs.kind === "any") return true;
    if (fs.kind === "empty") return false;
    const code = input.codePointAt(pos);
    if (code === void 0) return false;
    for (const r of fs.ranges) if (code >= r.lo && code <= r.hi) return true;
    return false;
  }
  function sepBy(combinator, separator) {
    const meta = {
      firstSet: combinator._meta.firstSet,
      canMatchNewline: combinator._meta.canMatchNewline || separator._meta.canMatchNewline,
      isTrivia: false
    };
    return {
      _tag: "sepBy",
      _meta: meta,
      _def: { tag: "sepBy", parser: combinator, separator },
      parse(input, pos, ctx) {
        const first = combinator.parse(input, pos, ctx);
        if (!first.ok) return { ok: true, value: [], span: { start: pos, end: pos } };
        const values = [first.value];
        let cur = first.span.end;
        while (cur < input.length) {
          const loopMark = saveTriviaMark(ctx);
          let sepPos = cur;
          if (ctx.trivia) {
            if (needsDeferredTriviaCommit(ctx)) {
              const scan = scanTrivia(input, cur, ctx);
              scan.commit();
              sepPos = scan.end;
            } else {
              sepPos = advanceTrivia(input, cur, ctx);
            }
          }
          const sep = separator.parse(input, sepPos, ctx);
          if (!sep.ok) {
            rollbackTrivia(ctx, loopMark);
            break;
          }
          let nextPos = sep.span.end;
          if (ctx.trivia) {
            if (needsDeferredTriviaCommit(ctx)) {
              const scan = scanTrivia(input, sep.span.end, ctx);
              scan.commit();
              nextPos = scan.end;
            } else {
              nextPos = advanceTrivia(input, sep.span.end, ctx);
            }
          }
          const next = combinator.parse(input, nextPos, ctx);
          if (!next.ok) {
            rollbackTrivia(ctx, loopMark);
            break;
          }
          values.push(next.value);
          cur = next.span.end;
        }
        return { ok: true, value: values, span: { start: pos, end: cur } };
      }
    };
  }

  // src/combinators/ref.ts
  function ref() {
    let resolved = null;
    const meta = {
      firstSet: any(),
      canMatchNewline: true,
      isTrivia: false
    };
    const slot = {
      _tag: "lazy",
      _meta: meta,
      _def: {
        tag: "lazy",
        thunk: () => {
          if (!resolved) throw new Error("ref<T>() used before .define() was called");
          return resolved;
        }
      },
      parse(input, pos, ctx) {
        if (!resolved) throw new Error("ref<T>() used before .define() was called");
        return resolved.parse(input, pos, ctx);
      },
      define(p) {
        if (resolved) throw new Error("ref<T>() already defined");
        resolved = p;
        meta.firstSet = p._meta.firstSet;
        meta.canMatchNewline = p._meta.canMatchNewline;
        meta.isTrivia = p._meta.isTrivia;
        if (p._meta.triviaKindLabels !== void 0) meta.triviaKindLabels = p._meta.triviaKindLabels;
        else delete meta.triviaKindLabels;
        if (p._meta.disjoint !== void 0) meta.disjoint = p._meta.disjoint;
        else delete meta.disjoint;
      }
    };
    return slot;
  }

  // src/compiler/value-usage.ts
  function markUnusedValues(root) {
    const seenConsumed = /* @__PURE__ */ new WeakSet();
    const seenUnconsumed = /* @__PURE__ */ new WeakSet();
    const mark = (def, consumed) => {
      if (consumed) def.valueUnused = false;
      else if (def.valueUnused !== false) def.valueUnused = true;
    };
    const visit = (c, consumed) => {
      const seen = consumed ? seenConsumed : seenUnconsumed;
      if (seen.has(c)) return;
      seen.add(c);
      const def = c._def;
      switch (def.tag) {
        case "many":
        case "oneOrMore":
          mark(def, consumed);
          visit(def.parser, consumed);
          return;
        case "optional":
          visit(def.parser, consumed);
          return;
        case "sequence":
          mark(def, consumed);
          for (const p of def.parsers) visit(p, consumed);
          return;
        case "choice":
          for (const p of def.parsers) visit(p, consumed);
          return;
        case "node":
          visit(def.parser, false);
          return;
        case "transform":
          visit(def.parser, true);
          return;
        case "field":
          visit(def.parser, true);
          return;
        case "skip":
          visit(def.main, consumed);
          visit(def.skipped, false);
          return;
        case "sepBy":
          visit(def.parser, true);
          visit(def.separator, false);
          return;
        case "not":
          visit(def.parser, false);
          return;
        case "grammar":
          visit(def.parser, consumed);
          if (def.triviaParser) visit(def.triviaParser, false);
          return;
        case "recover":
          visit(def.parser, consumed);
          visit(def.sentinel, false);
          return;
        case "label":
        case "trivia":
        case "token":
        case "withCtx":
        case "expect":
          visit(def.parser, consumed);
          return;
        case "lazy":
          return;
        default:
          return;
      }
    };
    const resolveRoot = (c) => {
      const guard2 = /* @__PURE__ */ new Set();
      let cur = c;
      while (!guard2.has(cur)) {
        const d = cur._def;
        if (d.tag !== "lazy") return cur;
        guard2.add(cur);
        try {
          cur = d.thunk();
        } catch {
          return c;
        }
      }
      return cur;
    };
    visit(resolveRoot(root), true);
  }

  // src/combinators/parser.ts
  function tagRule(r, key) {
    ;
    r._ruleName = key;
    if (r._def.tag === "node" && r._def.type === void 0) r._def.type = key;
  }
  function rules(factory) {
    const cache = {};
    const proxy = new Proxy(cache, {
      get(target, key) {
        if (typeof key !== "string") return void 0;
        const record = target;
        if (!(key in record)) {
          const r = ref();
          tagRule(r, key);
          record[key] = r;
        }
        return record[key];
      }
    });
    const definitions = factory(proxy);
    for (const key of Object.keys(definitions)) {
      const placeholder = cache[key];
      const parser2 = definitions[key];
      if (placeholder !== void 0 && typeof placeholder.define === "function") {
        tagRule(parser2, key);
        placeholder.define(parser2);
        placeholder._meta.firstSet = parser2._meta.firstSet;
        placeholder._meta.canMatchNewline = parser2._meta.canMatchNewline;
      } else {
        tagRule(parser2, key);
        cache[key] = parser2;
      }
    }
    for (const key of Object.keys(definitions)) {
      markUnusedValues(cache[key]);
    }
    return cache;
  }

  // src/combinators/map.ts
  function transform(combinator, fn) {
    return {
      _tag: "transform",
      _meta: combinator._meta,
      _def: { tag: "transform", parser: combinator, fn },
      parse(input, pos, ctx) {
        const result = combinator.parse(input, pos, ctx);
        if (!result.ok) return result;
        return { ok: true, value: fn(result.value, result.span), span: result.span };
      }
    };
  }
  function trivia(combinator) {
    const kindLabels = analyzeLabeledTrivia(combinator)?.labels;
    return {
      _tag: combinator._tag,
      _meta: {
        ...combinator._meta,
        isTrivia: true,
        ...kindLabels ? { triviaKindLabels: kindLabels } : {}
      },
      _def: { tag: "trivia", parser: combinator },
      parse: combinator.parse.bind(combinator)
    };
  }
  function label(name, combinator) {
    return {
      _tag: combinator._tag,
      _meta: combinator._meta,
      _def: { tag: "label", label: name, parser: combinator },
      parse(input, pos, ctx) {
        const result = combinator.parse(input, pos, ctx);
        if (!result.ok) return { ok: false, expected: [name], span: result.span };
        return result;
      }
    };
  }

  // src/compiler/line-index.ts
  function buildLineIndex(input) {
    const lineStarts = [0];
    for (let i = 0; i < input.length; i++) {
      if (input.charCodeAt(i) === 10) lineStarts.push(i + 1);
    }
    return { lineStarts };
  }
  function offsetToLineCol(index, offset) {
    const { lineStarts } = index;
    let lo = 0;
    let hi = lineStarts.length - 1;
    while (lo < hi) {
      const mid = lo + hi + 1 >> 1;
      if (lineStarts[mid] <= offset) lo = mid;
      else hi = mid - 1;
    }
    return { line: lo + 1, col: offset - lineStarts[lo] + 1 };
  }
  function annotateSpan(span, index) {
    const s = offsetToLineCol(index, span.start);
    const e = offsetToLineCol(index, span.end);
    return {
      ...span,
      startLine: s.line,
      startColumn: s.col,
      endLine: e.line,
      endColumn: e.col
    };
  }

  // src/combinators/grammar.ts
  function parser(opts, root) {
    const clearTrivia = opts.trivia === null;
    return {
      _tag: "grammar",
      _meta: root._meta,
      _def: {
        tag: "grammar",
        parser: root,
        triviaParser: clearTrivia ? void 0 : opts.trivia ?? void 0,
        clearTrivia,
        trackLines: opts.trackLines ?? false
      },
      parse(input, pos, _ctx) {
        const trackLines = opts.trackLines ?? _ctx?.trackLines ?? false;
        const ctx = {
          ..._ctx,
          trackLines,
          // trivia: null clears (contiguous terms); a Combinator sets; undefined inherits.
          ...clearTrivia ? {
            trivia: void 0,
            triviaKindLabels: void 0
          } : opts.trivia != null ? {
            trivia: opts.trivia,
            ...opts.trivia._meta.triviaKindLabels ? { triviaKindLabels: opts.trivia._meta.triviaKindLabels } : {}
          } : {},
          ...opts.captureTrivia || _ctx?.captureTrivia ? { captureTrivia: true } : {}
        };
        const result = root.parse(input, pos ?? 0, ctx);
        if (trackLines) {
          const idx = buildLineIndex(input);
          return { ...result, span: annotateSpan(result.span, idx) };
        }
        return result;
      }
    };
  }

  // src/compiler/scannable-run.ts
  var META = new Set("()[]{}*+?|^$.".split(""));

  // src/compiler/trivia-fast-path.ts
  var CAP_RECORD = [
    `  if (_cap && _e > _pos) {`,
    `    if (_ctx._triviaLog !== undefined) _ctx._triviaLog.push(_pos, _e)`,
    `    if (_ctx._cstTriviaLog !== undefined) _ctx._cstTriviaLog.push(_pos, _e, _ctx._cstRawChildren ? _ctx._cstRawChildren.length : 0)`,
    `  }`
  ].join("\n");

  // src/cst/offset-model.ts
  var { isFinite } = Number;

  // src/index.ts
  registerRegexAnalyzer(firstSetFromRegex);

  // examples/json/chevrotain-bench.ts
  var ws = trivia(regex(/[ \t\n\r]*/));
  var stringToken = label("string", regex(/"(?:[^\\"]|\\(?:[bfnrtv"\\/]|u[0-9a-fA-F]{4}))*"/));
  var numberToken = label("number", regex(/-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?/));
  var voidOf = (c) => transform(c, () => void 0);
  var { jsonValue } = rules((g) => {
    const comma = literal(",");
    const jsonObject = voidOf(sequence(
      literal("{"),
      optional(sepBy(
        sequence(stringToken, literal(":"), g.jsonValue),
        comma
      )),
      literal("}")
    ));
    const jsonArray = voidOf(sequence(
      literal("["),
      optional(sepBy(g.jsonValue, comma)),
      literal("]")
    ));
    return {
      jsonValue: choice(
        voidOf(stringToken),
        voidOf(numberToken),
        jsonObject,
        jsonArray,
        voidOf(literal("true")),
        voidOf(literal("false")),
        voidOf(literal("null"))
      )
    };
  });
  var jsonRecognize = parser({ trivia: ws }, jsonValue);

  // scripts/chevrotain-bench-interpreter-entry.ts
  window.parse = function parse_json_parseman_interpreted(input) {
    const result = jsonRecognize.parse(input);
    if (!result.ok) {
      throw new SyntaxError(
        "JSON parse error at offset " + result.span.start + ": expected " + result.expected.join(" or ")
      );
    }
    return result;
  };
})();
